---
title: "assignment1"
author: "vkvats"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2.1. Find the sid and rating of each sailor.  

**Ans**: {$(s.sid, s.rating)| Sailor(s)$}  

## 2.2 Find the sid, name, and rating of each sailor whose rating is in the range [2;11] but not in the range [8;10].  

**Ans**: {$(s.sid, s.name, s.rating)| Sailor(s) \land ((s.rating \geq 2 \land s.rating < 8) \lor(s.rating > 10 \land s.rating\leq 11))$}  

## 2.3. Find the bid, name, and color of each non-red boat that was reserved by some sailor whose rating is more than 7.  

**Ans**: {$(b.bid, b.name, b.color) | Boat(b) \land (\exists_r \exists_s (Reserves(r) \land Sailor(s) \land (r.bid = b.bid) \land (r.sid = s.sid) \land (s.rating > 7) \land (b.color \neq Red)))$}  

## 2.4. Find the bid and name of each boat that was reserved by a sailor on a weekend day but that was not reserved by a sailor on a Tuesday.  

**Ans**: {$(b.bid, b.name) | Boat(b) \land \exists_{r1} (Reserves(r1) \land (b.bid = r1.bid) \land (r1.day = Saturday \lor r1.day = Sunday)) \land \neg\exists_{r2} (Reserves(r2) \land (b.bid = r2.bid) \land (r2.day = Tuesday))$}  

## 2.5. Find the sid of each sailor who reserved both a red boat and a green boat.  

**Ans**: {$(r1.sid) | Reserves(r1) \land \exists_{b1}\exists_{r2} \exists_{b2}( Boat(b1) \land (b1.bid = r1.bid ) \land (b1.color = Red) \land Reserves(r2) \land  Boat(b2) \land  (b2.bid = r2.bid ) \land (b2.color = Green) \land (r1.sid = r2.sid))$}  

## 2.6. Find the sid and name of each each sailor who reserved at least two different boats.  

**Ans**: {$(s.sid, s.name) | Sailor(s) \land \exists_{r1} \exists_{r2} (Reserves(r1) \land (Reserves(r2) \land (s.sid = r1.sid) \land (s.sid = r2.sid) \land (r1.bid \neq r2.bid)))$}  

## 2.7. Find the pairs of sids (s1; s2) of different sailors who both reserved a same boat. 

**Ans**: {$(r1.sid, r2.sid) | Reserves(r1) \land  Reserves(r2) \land (r1.bid = r2.bid) \land (r1.sid \neq r2.sid)$}  

## 2.8. Find the sid of each sailor who did not reserve any boats on a Monday or on a Tuesday.  

**Ans**: {$(s.sid) | Sailor(s) \land \neg(\exists_{r} (Reserves(r) \land (s.sid = r.sid) \land (r.day = Monday \lor r.day = Tuesday )))$}  

## 2.9. Find the pairs (s; b) such that the sailor with sid s reserved the boat with bid b, provided that the sailor s has a rating greater than 6 and the color of boat b is not red.  

**Ans**: {$(s.sid, b.bid) | Sailor(s) \land  Boat(b) \land \exists_r( Reserves(r) \land (b.bid = r.bid) \land ( s.sid = r.sid) \land (b.color \neq Red) \land (s.rating > 6))$}  

## 2.10. Find the bid of each boat that where reserved by just one sailor.  

**Ans**: {$(r1.bid) | Reserves(r1) \land \neg \exists_{r2}(Reserves(r2) \land (r1.bid = r2.bid) \land (r1.sid \ne r2.sid))$}  

## 2.11. Find the sid of each sailor who reserved fewer than 3 boats.  

**Ans**: {$(s.sid) | Sailor(s) \land \neg(\exists_{r1} \exists_{r1} \exists_{r3} (Reserves(r1) \land (Reserves(r2) \land  (Reserves(r3) \land (s.sid = r1.sid) \land (s.sid = r2.sid) \land (s.sid = r3.sid) \land (r1.bid \ne r2.bid) \land (r1.bid \ne r3.bid) \land (r3.bid \ne r2.bid)))))$}  





















